name: Benchmark

on:
  push:
    branches: [master]

jobs:

  benchmark:
    runs-on: ubuntu-latest
    if: contains(github.event.commits[0].message, '[benchmark]')
    env:
      DOCKER_USERNAME_SECRET: ${{ secrets.DOCKER_USERNAME_SECRET }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: docker run -p 5432:5432 -e POSTGRES_PASSWORD=password -d postgres:latest
    - run: docker run -p 6379:6379 -d redislabs/redisearch:latest
    - run: docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -d elasticsearch:7.16.2
    - run: docker run -p 20000:20000 -d ${{ env.DOCKER_USERNAME_SECRET }}/coba:latest
    - run: cd etc ; npm init -y ; npm i jest-diff coba-storage ioredis elasticsearch pg ejz-utils @node-redis/search
    - run: node etc/benchmark 100000
