name: CI

on:
  push:
    branches: [master]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm test
  
  npm-publish:
    needs: [test]
    env:
      NPM_TOKEN_SECRET: ${{ secrets.NPM_TOKEN_SECRET }}
    runs-on: ubuntu-latest
    if: contains(github.event.commits[0].message, '[publish]') || contains(github.event.commits[0].message, '[npm-publish]')
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm i
    - run: npm run build
    - run: echo -n '//registry.npmjs.org/:_authToken=' >dist/.npmrc
    - run: echo $NPM_TOKEN_SECRET >>dist/.npmrc
    - run: cd dist && npm publish

  docker-publish:
    needs: [npm-publish]
    runs-on: ubuntu-latest
    if: contains(github.event.commits[0].message, '[publish]') || contains(github.event.commits[0].message, '[docker-publish]')
    env:
      DOCKER_USERNAME_SECRET: ${{ secrets.DOCKER_USERNAME_SECRET }}
      DOCKER_TOKEN_SECRET: ${{ secrets.DOCKER_TOKEN_SECRET }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME_SECRET }}
        password: ${{ env.DOCKER_TOKEN_SECRET }}
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        push: true
        tags: ${{ env.DOCKER_USERNAME_SECRET }}/coba:latest
