name: CI

on:
  push:
    branches: [master]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
  
  publish:
    needs: [test]
    env:
      NPM_TOKEN_SECRET: ${{ secrets.NPM_TOKEN_SECRET }}
    runs-on: ubuntu-latest
    if: contains(github.ref, "[publish]")
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - run: echo -n '//registry.npmjs.org/:_authToken=' >.npmrc
    - run: echo $NPM_TOKEN_SECRET >>.npmrc
    - run: npm ci
    - run: npm publish
